openapi: 3.0.0
info:
  title: Car system API.
  description: Managing car.
  version: 1.0.0
tags:
  - name: Car_info
    description: All operation in system
externalDocs:
  url: https://www.youtube.com/@NerdiCoda
  description: My Car API     